service: julledev-api

provider:
  name: aws
  runtime: nodejs12.x
  region: 'us-east-1'
  stage: prod
  memorySize: 256
  timeout: 5
  apiGateway:
    minimumCompressionSize: 1024
    usagePlan:
      quota:
        limit: 5000
        offset: 4
        period: MONTH
      throttle:
        burstLimit: 10
        rateLimit: 5

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline-dotenv
  - serverless-offline
  - serverless-domain-manager

custom:
  webpack:
    webpackConfig: './webpack.config.ts'
    includeModules:
      packagePath: './package.json'
    packager: 'yarn'
  serverless-offline:
    httpPort: 3000
  customDomain:
    domainName: 'api.julle.dev'
    certificateName: 'julle.dev'
    createRoute53Record: true

functions:
  contact:
    handler: src/contact.handler
    reservedConcurrency: 1
    environment:
      TG_TOKEN: ${ssm:/tg-token~true}
      TG_CHAT_ID: ${ssm:/tg-chat-id~true}
    events:
      - http:
          path: /contact
          method: post
          cors: true
