service: julledev-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  memorySize: 512
  timeout: 5
  apiGateway:
    minimumCompressionSize: 1024
    usagePlan:
      quota:
        limit: 5000
        offset: 3
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

custom:
  webpack:
    webpackConfig: './webpack.config.ts'
    includeModules:
      packagePath: './package.json'
    packager: 'yarn'
  serverless-offline:
    httpPort: 3000
  customDomain:
    domainName: 'api.julle.dev'
    certificateName: 'julle.dev'
    createRoute53Record: true

functions:
  contact:
    handler: src/contact.handler
    events:
      - http:
          path: /contact
          method: post
          cors: true
