service: julledev-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  memorySize: 512
  timeout: 5
  apiGateway:
    minimumCompressionSize: 1024
    usagePlan:
      quota:
        limit: 500
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 20
        rateLimit: 10

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: './webpack.config.ts'
    includeModules:
      packagePath: './package.json'
      forceExclude:
        - aws-sdk
    packager: 'yarn'
  serverless-offline:
    httpPort: 3000

functions:
  contact:
    handler: src/contact.handler
    events:
      - http:
          path: /contact
          method: post
          cors: true
