name: API

on:
  push:
    branches:
      - master
      - actions

jobs:
  deploy-api:
    name: Deploying API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.ENV }}
          EOF
      - name: Install dependencies
        working-directory: ./api
        run: yarn install
      - name: Serverless authentication
        working-directory: ./api
        run: yarn run sls config --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
      - name: Deploy lambdas
        working-directory: ./api
        run: yarn run psls deploy -s prod