name: API

on:
  push:
    branches:
      - master
      - actions

jobs:
  deploy-api:
    name: Deploying API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.ENV }}
          EOF
      - name: Serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          SERVICE_ROOT: 'api'
          AWS_ACCESS_KEY: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}